---
# tasks file for DVWA-ansible

- name: 'Validate action vars'
  assert:
    that:
      - action in role_actions
  tags:
    - always

- name: 'Include action tasks'
  include_task: '{{ action }}.yml'
  tags:
    - always
